# Generated by Django 2.2 on 2019-04-23 02:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('essays', '0001_initial'),
        ('exams', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Grade',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('so1', models.IntegerField()),
                ('so2', models.IntegerField()),
                ('so3', models.IntegerField()),
                ('so4', models.IntegerField()),
                ('so5', models.IntegerField()),
                ('so6', models.IntegerField()),
                ('mahasiswa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grades', to='essays.Student')),
                ('penguji', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='grades', to='exams.Penguji')),
            ],
            options={
                'db_table': 'students_grades',
            },
        ),
    ]
