# Generated by Django 2.2 on 2019-05-04 04:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('grades', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentOutcome',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('judul', models.CharField(max_length=5)),
                ('deksripsi', models.TextField()),
            ],
        ),
        migrations.RemoveField(
            model_name='grade',
            name='so1',
        ),
        migrations.RemoveField(
            model_name='grade',
            name='so2',
        ),
        migrations.RemoveField(
            model_name='grade',
            name='so3',
        ),
        migrations.RemoveField(
            model_name='grade',
            name='so4',
        ),
        migrations.RemoveField(
            model_name='grade',
            name='so5',
        ),
        migrations.RemoveField(
            model_name='grade',
            name='so6',
        ),
        migrations.AddField(
            model_name='grade',
            name='nilai',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='grade',
            name='so',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='grades.StudentOutcome'),
        ),
    ]
