# Generated by Django 2.2 on 2019-05-04 04:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exam',
            name='status',
            field=models.IntegerField(choices=[(1, 'Belum Mulai'), (2, 'Sedang Berlangsung'), (3, 'Selesai')]),
        ),
    ]
