# Generated by Django 2.2 on 2019-05-04 07:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0004_auto_20190504_1422'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exam',
            name='skripsi',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='exams', to='essays.Essay'),
        ),
    ]
