# Generated by Django 2.2 on 2019-05-04 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0005_auto_20190504_1437'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exam',
            name='status',
            field=models.IntegerField(blank=True, choices=[(3, 'Selesai'), (2, 'Sedang Berlangsung'), (1, 'Belum Mulai')], null=True),
        ),
    ]
