# Generated by Django 2.2 on 2019-05-04 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0006_auto_20190504_1446'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exam',
            name='status',
            field=models.IntegerField(blank=True, choices=[(3, 'Selesai'), (1, 'Belum Mulai'), (2, 'Sedang Berlangsung')], null=True),
        ),
    ]
