# Generated by Django 2.2.3 on 2019-07-22 03:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Essay',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('judul', models.CharField(max_length=250)),
                ('intisari', models.TextField()),
                ('naskah', models.CharField(blank=True, max_length=250, null=True)),
                ('is_capstone', models.BooleanField()),
                ('title_revision', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('pembimbing_dua', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pembimbing_dua', to=settings.AUTH_USER_MODEL)),
                ('pembimbing_satu', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pembimbing_satu', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Essay',
                'verbose_name_plural': 'Essays',
                'db_table': 'essays',
                'ordering': ('created_at',),
            },
        ),
        migrations.CreateModel(
            name='TitleRevision',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('revisi', models.TextField()),
                ('skripsi', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='revision', to='essays.Essay')),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=250)),
                ('nim', models.CharField(max_length=30, verbose_name='Nomor Induk Mahasiswa')),
                ('prodi', models.CharField(max_length=20, verbose_name='Program Studi')),
                ('konsentrasi', models.CharField(max_length=50)),
                ('tempat_lahir', models.CharField(max_length=50, verbose_name='Tempat Lahir')),
                ('tanggal_lahir', models.DateField(verbose_name='Tanggal Lahir')),
                ('telepon', models.CharField(max_length=20)),
                ('skripsi', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='students', to='essays.Essay')),
            ],
            options={
                'verbose_name': 'Student',
                'verbose_name_plural': 'Students',
                'db_table': 'students',
            },
        ),
    ]
