# Generated by Django 2.2 on 2019-05-04 04:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('essays', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='essay',
            name='naskah',
            field=models.FileField(blank=True, upload_to='skripsi/%Y/%m/%d/'),
        ),
    ]
