# Generated by Django 2.2 on 2019-05-04 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('essays', '0002_auto_20190504_1131'),
    ]

    operations = [
        migrations.AlterField(
            model_name='essay',
            name='naskah',
            field=models.FileField(blank=True, null=True, upload_to='skripsi/%Y/%m/%d/'),
        ),
    ]
