# Generated by Django 2.2 on 2019-05-04 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('essays', '0003_auto_20190504_1419'),
    ]

    operations = [
        migrations.AlterField(
            model_name='essay',
            name='naskah',
            field=models.FileField(upload_to='skripsi/%Y/%m/%d/'),
        ),
    ]
