# Generated by Django 2.2 on 2019-04-23 02:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('essays', '0001_initial'),
        ('exams', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bab', models.CharField(max_length=30)),
                ('halaman', models.IntegerField()),
                ('komentar', models.TextField()),
                ('penguji', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='comments', to='exams.Penguji')),
                ('skripsi', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='essays.Essay')),
            ],
            options={
                'db_table': 'essays_comments',
            },
        ),
    ]
