# Generated by Django 2.2.3 on 2019-07-22 03:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('exams', '0001_initial'),
        ('essays', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bab', models.IntegerField(choices=[(1, 'Pendahuluan'), (6, 'Umum'), (0, 'Abstrak'), (4, 'Hasil dan Pembahasan'), (5, 'Kesimpulan'), (3, 'Metode Penelitian'), (2, 'Dasar Teori')])),
                ('halaman', models.IntegerField(blank=True, null=True)),
                ('komentar', models.TextField()),
                ('penguji', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='exams.Penguji')),
                ('skripsi', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='essays.Essay')),
            ],
            options={
                'db_table': 'essays_comments',
            },
        ),
    ]
