# Generated by Django 2.2.3 on 2019-07-22 03:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('nama', models.CharField(blank=True, max_length=250)),
                ('email', models.EmailField(max_length=50, unique=True, verbose_name='Alamat Email')),
                ('nip', models.CharField(blank=True, max_length=20, verbose_name='Nomor Induk Pegawai')),
                ('prodi', models.CharField(blank=True, choices=[('TI', 'Teknologi Informasi'), ('TE', 'Teknik Elektro')], max_length=20, null=True, verbose_name='Program Studi')),
                ('konsentrasi', models.CharField(blank=True, max_length=50, null=True)),
                ('foto', models.CharField(blank=True, max_length=250, null=True)),
                ('is_admin', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'User',
                'verbose_name_plural': 'Users',
                'db_table': 'users',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='Pengelola',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jabatan', models.CharField(blank=True, max_length=250, null=True)),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Pengelola',
                'verbose_name_plural': 'Pengelola',
                'db_table': 'pengelola',
            },
        ),
    ]
