# Generated by Django 2.2 on 2019-04-18 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('nama', models.CharField(blank=True, max_length=50)),
                ('email', models.EmailField(max_length=50, unique=True, verbose_name='alamat email')),
                ('nip', models.CharField(blank=True, max_length=20, verbose_name='Nomor Induk Pegawai')),
                ('prodi', models.CharField(blank=True, choices=[('TE', 'Teknik Elektro'), ('TI', 'Teknologi Informasi')], max_length=20, null=True)),
                ('konsentrasi', models.CharField(blank=True, max_length=50, null=True)),
                ('is_admin', models.BooleanField(default=False)),
                ('last_login', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'User',
                'verbose_name_plural': 'Users',
                'db_table': 'users',
            },
        ),
    ]
