# Generated by Django 2.1.7 on 2019-04-02 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='konsentrasi',
            field=models.CharField(blank=True, choices=[('RPL', 'Rekayasa Perangkat Lunak'), ('RSK', 'Rekayasa Sistem Komputer'), ('RSI', 'Rekayasa Sistem Informasi')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='prodi',
            field=models.CharField(blank=True, choices=[('TE', 'Teknik Elektro'), ('TI', 'Teknologi Informasi')], max_length=20, null=True),
        ),
    ]
