# Generated by Django 2.2 on 2019-04-07 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20190405_2101'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='konsentrasi',
            field=models.CharField(blank=True, choices=[('RPL', 'Rekayasa Perangkat Lunak'), ('RSI', 'Rekayasa Sistem Informasi'), ('RSK', 'Rekayasa Sistem Komputer')], max_length=50, null=True),
        ),
    ]
